<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB5ZvyVK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB5ZvyVK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB5ZvyVK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB5ZvyVK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB5ZvyVK\App_KernelDevDebugContainer([
    'container.build_hash' => 'B5ZvyVK',
    'container.build_id' => 'afccaed9',
    'container.build_time' => 1587404631,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB5ZvyVK');
