<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVAIyJpH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVAIyJpH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVAIyJpH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVAIyJpH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVAIyJpH\App_KernelDevDebugContainer([
    'container.build_hash' => 'VAIyJpH',
    'container.build_id' => '81aa2915',
    'container.build_time' => 1587136555,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVAIyJpH');
