<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWHvKiqF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWHvKiqF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWHvKiqF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWHvKiqF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWHvKiqF\App_KernelDevDebugContainer([
    'container.build_hash' => 'WHvKiqF',
    'container.build_id' => '2346a679',
    'container.build_time' => 1585000346,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWHvKiqF');
